#ifndef __LIBS_BASE_TASKS_M7_H__
#define __LIBS_BASE_TASKS_M7_H__

#include "libs/FreeRTOS/FreeRTOSConfig.h"
#define IPC_TASK_PRIORITY           (configMAX_PRIORITIES - 1)
#define CONSOLE_TASK_PRIORITY       (configMAX_PRIORITIES - 2)
#define APP_TASK_PRIORITY           (configMAX_PRIORITIES - 2)
#define USB_DEVICE_TASK_PRIORITY    (configMAX_PRIORITIES - 1)
#define USB_HOST_TASK_PRIORITY      (configMAX_PRIORITIES - 1)
#define EDGETPU_DFU_TASK_PRIORITY   (configMAX_PRIORITIES - 2)
#define RANDOM_TASK_PRIORITY        (configMAX_PRIORITIES - 1)

#if defined(__cplusplus)
#define VALIDATE_TASK_PRIORITY(prio) \
    static_assert(prio < configMAX_PRIORITIES); \
    static_assert(prio >= 0);

VALIDATE_TASK_PRIORITY(IPC_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(CONSOLE_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(APP_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(USB_DEVICE_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(USB_HOST_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(EDGETPU_DFU_TASK_PRIORITY);
VALIDATE_TASK_PRIORITY(RANDOM_TASK_PRIORITY);

#endif

#endif  // __LIBS_BASE_TASKS_M7_H__
