#include "examples/FlexSPI_NAND/flexspi_nand_lut.h"
#include "third_party/nxp/rt1176-sdk/devices/MIMXRT1176/drivers/fsl_flexspi.h"
#include "third_party/nxp/rt1176-sdk/devices/MIMXRT1176/drivers/fsl_romapi.h"

const uint32_t customLUT[64] = {
    [4 * LUT_READ_FROM_CACHE]     = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0xEB, CADDR_SDR, FLEXSPI_4PAD, 0x10),
    [4 * LUT_READ_FROM_CACHE + 1] = FLEXSPI_LUT_SEQ(DUMMY_SDR, FLEXSPI_4PAD, 0x04, READ_SDR, FLEXSPI_4PAD, 0x80),
    [4 * LUT_READ_STATUS]         = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x0F, CMD_SDR, FLEXSPI_1PAD, 0xC0),
    [4 * LUT_READ_STATUS + 1]     = FLEXSPI_LUT_SEQ(READ_SDR, FLEXSPI_1PAD, 0x01, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_READID]              = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x9F, DUMMY_SDR, FLEXSPI_1PAD, 0x8),
    [4 * LUT_READID + 1]          = FLEXSPI_LUT_SEQ(READ_SDR, FLEXSPI_1PAD, 0x02, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_WRITE_ENABLE]        = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x06, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_RESET]               = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0xFF, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_BLOCK_ERASE]         = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0xD8, RADDR_SDR, FLEXSPI_1PAD, 0x18),
    [4 * LUT_UNLOCK]              = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x1F, CMD_SDR, FLEXSPI_1PAD, 0xA0),
    [4 * LUT_UNLOCK + 1]          = FLEXSPI_LUT_SEQ(WRITE_SDR, FLEXSPI_1PAD, 0x1, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_PROGRAM_LOAD]        = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x32, CADDR_SDR, FLEXSPI_1PAD, 0x10),
    [4 * LUT_PROGRAM_LOAD + 1]    = FLEXSPI_LUT_SEQ(WRITE_SDR, FLEXSPI_4PAD, 0x40, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_READ_PAGE]           = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x13, RADDR_SDR, FLEXSPI_1PAD, 0x18),
    [4 * LUT_READ_ECC_STATUS]     = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x0F, CMD_SDR, FLEXSPI_1PAD, 0xC0),
    [4 * LUT_READ_ECC_STATUS + 1] = FLEXSPI_LUT_SEQ(READ_SDR, FLEXSPI_1PAD, 0x01, STOP, FLEXSPI_1PAD, 0),
    [4 * LUT_PROGRAM_EXECUTE]     = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x10, RADDR_SDR, FLEXSPI_1PAD, 0x18),
    [4 * LUT_READ_LOCK_STATUS]     = FLEXSPI_LUT_SEQ(CMD_SDR, FLEXSPI_1PAD, 0x0F, CMD_SDR, FLEXSPI_1PAD, 0xA0),
    [4 * LUT_READ_LOCK_STATUS + 1] = FLEXSPI_LUT_SEQ(READ_SDR, FLEXSPI_1PAD, 0x01, STOP, FLEXSPI_1PAD, 0),
};
